# Generated by Django 6.0.3 on 2026-03-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="draw",
            name="draw_type",
            field=models.CharField(
                choices=[("random", "Random"), ("manual", "Manual")], max_length=20
            ),
        ),
    ]
