from django.urls import path

from .draw_views import (
    AdminAnalyticsView,
    AdminCharityDetailView,
    AdminCharityView,
    AdminDrawListCreateView,
    AdminDrawPublishView,
    AdminMarkPaidView,
    AdminRunDrawView,
    AdminUserDetailView,
    AdminUserListView,
    AdminUserScoresView,
    AdminVerifyWinnerView,
    AdminWinnersListView,
    CurrentDrawView,
    DrawHistoryView,
    UploadWinnerProofView,
    UserDrawEntriesView,
    UserWinningsView,
)
from .stripe_views import (
    CancelSubscriptionView,
    CreateCheckoutSessionView,
    StripeWebhookView,
    SubscriptionPlanListView,
    SubscriptionStatusView,
)

from .views import (
    CharityDetailView,
    CharityListView,
    GolfScoreListCreateView,
    GolfScoreUpdateDeleteView,
    LoginView,
    LogoutView,
    RegisterView,
    SelectCharityView,
    UserProfileView,
)

urlpatterns = [
    path("auth/register/", RegisterView.as_view(), name="auth-register"),
    path("auth/login/", LoginView.as_view(), name="auth-login"),
    path("auth/logout/", LogoutView.as_view(), name="auth-logout"),
    path("user/profile/", UserProfileView.as_view(), name="user-profile"),
    path("user/select-charity/", SelectCharityView.as_view(), name="user-select-charity"),
    path("charities/", CharityListView.as_view(), name="charity-list"),
    path("charities/<slug:slug>/", CharityDetailView.as_view(), name="charity-detail"),
    path("scores/", GolfScoreListCreateView.as_view(), name="score-list-create"),
    path("scores/<int:pk>/", GolfScoreUpdateDeleteView.as_view(), name="score-update-delete"),
    path("subscription/plans/", SubscriptionPlanListView.as_view(), name="subscription-plans"),
    path("subscription/checkout/", CreateCheckoutSessionView.as_view(), name="subscription-checkout"),
    path("subscription/webhook/", StripeWebhookView.as_view(), name="subscription-webhook"),
    path("subscription/cancel/", CancelSubscriptionView.as_view(), name="subscription-cancel"),
    path("subscription/status/", SubscriptionStatusView.as_view(), name="subscription-status"),
    path("draws/current/", CurrentDrawView.as_view(), name="draw-current"),
    path("draws/history/", DrawHistoryView.as_view(), name="draw-history"),
    path("draws/my-entries/", UserDrawEntriesView.as_view(), name="draw-my-entries"),
    path("draws/my-winnings/", UserWinningsView.as_view(), name="draw-my-winnings"),
    path("draws/upload-proof/<int:pk>/", UploadWinnerProofView.as_view(), name="draw-upload-proof"),
    path("admin/draws/", AdminDrawListCreateView.as_view(), name="admin-draws"),
    path("admin/draws/<int:pk>/run/", AdminRunDrawView.as_view(), name="admin-draw-run"),
    path("admin/draws/<int:pk>/publish/", AdminDrawPublishView.as_view(), name="admin-draw-publish"),
    path("admin/winners/", AdminWinnersListView.as_view(), name="admin-winners"),
    path("admin/winners/<int:pk>/verify/", AdminVerifyWinnerView.as_view(), name="admin-winner-verify"),
    path("admin/winners/<int:pk>/mark-paid/", AdminMarkPaidView.as_view(), name="admin-winner-mark-paid"),
    path("admin/analytics/", AdminAnalyticsView.as_view(), name="admin-analytics"),
    path("admin/users/", AdminUserListView.as_view(), name="admin-users"),
    path("admin/users/<int:pk>/", AdminUserDetailView.as_view(), name="admin-user-detail"),
    path("admin/users/<int:pk>/scores/", AdminUserScoresView.as_view(), name="admin-user-scores"),
    path("admin/charities/", AdminCharityView.as_view(), name="admin-charities"),
    path("admin/charities/<int:pk>/", AdminCharityDetailView.as_view(), name="admin-charity-detail"),
]